print("Bienvenido a este pequeño generador aleatorio, para continuar da enter ")
bin = input ()
print ("")
print(" La Herramienta consiste en un sistema de generacion aleatorio, para comenzar da enter:")
Aceptar= input ()
from random import randrange
print ("==============")
print ("Bins Generados:=")
print ("==============")
print ("Bins=")
print ("=======")
print(randrange(400000, 600000))
print(randrange(400000, 600000))
print(randrange(400000, 600000))
print(randrange(400000, 600000))
print(randrange(400000, 600000))
print(randrange(400000, 600000))
print ("==============")
print ("ccv posibles y opcionales:=")
print ("==============")
print(randrange(100, 600))
print(randrange(100, 600))
print(randrange(100, 600))
print(randrange(100, 600))
print(randrange(100, 600))
print(randrange(100, 600))
print ("===============")
print ("Años posibles y opcionales:=")
print ("===============")
print(randrange(10, 30))
print(randrange(10, 30))
print(randrange(10, 30))
print(randrange(10, 30))
print(randrange(10, 30))
print(randrange(10, 30))
print ("===============")
print ("Dias posibles y opcionales:=")
print ("===============")
print(randrange(00, 29))
print(randrange(00, 29))
print(randrange(00, 29))
print(randrange(00, 29))
print(randrange(00, 29))
print(randrange(00, 29))
print ("Instrucciones de uso")
print ("Complete los 16 digitos con x y genere sus tarjetas")
print ("Los datos de fecha y ccv son opcionales")
print ("Una vez creados los bins pruben en las plataformas de preferencia")
print ("Para saber la IP del bin usen binscodes ")
print ("Sin mas que decir les deceo suerte")


print ("Herramienta de prueba by skelling oficial")

